version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    ports:
      - 3005:3005
    networks:
      - common-network
    env_file:
      - .env
  mysql-container:
    image: mysql
    volumes:
      - /Users/stephencurry/Documents/docker/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: mlz
    networks:
      - common-network
  redis-container:
    image: redis
    volumes:
      - /Users/stephencurry/Documents/docker/redis
    networks:
      - common-network
networks:
  common-network:
    driver: bridge
